#!/usr/bin/env python3
"""Generate data/frameworks/cis-v8.yaml — CIS Controls v8 identifiers only.

CIS Controls v8 are licensed CC BY-NC-ND 4.0 (see data/vendor/cis/LICENSE.md):
redistribution is non-commercial only, and transformed versions may not be
distributed. This repository is public.

So this generator deliberately does NOT emit CIS's Safeguard titles or their
normative statements. It takes only the identifiers and structure — facts, not
expression — from the official OSCAL serialisation, and pairs each with a
description written for this project in data/frameworks/cis-v8-descriptions.yaml.

That is the same line the ISO 27001 catalog draws: identifiers are referenceable,
normative text is not reproduced.

The output is checked before it is written: if any CIS title or statement string
appears in it, the generator fails rather than shipping the text.
"""
import re
import sys
from pathlib import Path
from xml.etree import ElementTree as ET

import yaml

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "data" / "vendor" / "cis" / "cis-controls-v8_OSCAL-1.0.xml"
DESCRIPTIONS = ROOT / "data" / "frameworks" / "cis-v8-descriptions.yaml"
OUT = ROOT / "data" / "frameworks" / "cis-v8.yaml"


def esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main() -> int:
    if not SRC.exists():
        print(f"missing source: {SRC}", file=sys.stderr)
        return 1

    root = ET.parse(SRC).getroot()
    ns = root.tag.split("}")[0].strip("{") if "}" in root.tag else ""
    q = (lambda t: f"{{{ns}}}{t}") if ns else (lambda t: t)

    def text(el):
        return " ".join("".join(el.itertext()).split()) if el is not None else ""

    ids, cis_text = [], []

    def walk(node):
        for c in node.findall(q("control")):
            cid = c.get("id", "").replace("cisc-", "")
            if cid:
                ids.append(cid)
                # Collected only so the leak check below can look for it.
                cis_text.append(text(c.find(q("title"))))
                for p in c.findall(q("part")):
                    if p.get("name") == "statement":
                        cis_text.append(text(p))
            walk(c)

    walk(root)
    for g in root.findall(q("group")):
        walk(g)

    desc = yaml.safe_load(DESCRIPTIONS.read_text(encoding="utf8"))
    controls = {str(k): v for k, v in (desc.get("controls") or {}).items()}
    safeguards = {str(k): v for k, v in (desc.get("safeguards") or {}).items()}

    top = sorted((i for i in ids if "." not in i), key=int)
    safe = sorted((i for i in ids if "." in i), key=lambda s: [int(p) for p in s.split(".")])

    missing = [i for i in top if i not in controls] + [i for i in safe if i not in safeguards]
    if missing:
        print(f"no authored description for: {missing[:10]}", file=sys.stderr)
        return 1
    extra = [k for k in list(controls) + list(safeguards) if k not in set(ids)]
    if extra:
        print(f"description for an identifier not in the catalog: {extra[:10]}", file=sys.stderr)
        return 1

    lines = [
        "# CIS Critical Security Controls v8 — identifiers with our own descriptions",
        "# ----------------------------------------------------------------------------",
        "# GENERATED by scripts/gen_cis_catalog.py — do not edit by hand.",
        "# Descriptions come from cis-v8-descriptions.yaml, which IS hand-written.",
        "#",
        "# LICENCE. CIS Controls v8 are CC BY-NC-ND 4.0 (data/vendor/cis/LICENSE.md):",
        "# non-commercial redistribution only, and transformed versions may not be",
        "# distributed. Accordingly this file carries CIS Safeguard IDENTIFIERS ONLY.",
        "# CIS's Safeguard titles and normative statements appear nowhere in this",
        "# repository — the descriptions below are ours, written for this project, and",
        "# any error in them is ours rather than a misquotation of CIS.",
        "#",
        "# Attribution: CIS Critical Security Controls v8, Center for Internet Security.",
        "# https://www.cisecurity.org/controls",
        "#",
        f"# {len(top)} Controls, {len(safe)} Safeguards.",
        "meta:",
        "  framework: CIS Critical Security Controls",
        '  version: "v8"',
        "  # Off until an organisation adopts it; see frameworks.enabled.",
        "  enabled: false",
        "  licence: CC BY-NC-ND 4.0 (Center for Internet Security) — identifiers only, descriptions ours",
        "  source_url: https://www.cisecurity.org/controls",
        "controls:",
    ]
    for cid in top:
        lines.append(f'  - {{ code: "{cid}", title: "{esc(controls[cid])}" }}')
    lines.append("safeguards:")
    for sid in safe:
        lines.append(
            f'  - {{ code: "{sid}", control: "{sid.split(".")[0]}", title: "{esc(safeguards[sid])}" }}'
        )
    body = "\n".join(lines) + "\n"

    # Refuse to ship CIS wording. Compare on normalised words so a near-copy is
    # caught, not just an exact one.
    def norm(s):
        return re.sub(r"[^a-z0-9 ]", " ", s.lower()).split()

    body_words = " ".join(norm(body))
    for t in cis_text:
        w = norm(t)
        if len(w) < 4:
            continue
        if " ".join(w) in body_words:
            print(f"REFUSING to write: output contains CIS wording -> {t[:70]!r}", file=sys.stderr)
            return 1

    OUT.write_text(body, encoding="utf8")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(top)} Controls, {len(safe)} Safeguards")
    print("  leak check: no CIS title or statement wording present in the output")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
