#!/usr/bin/env python3
"""Generate data/frameworks/sp800-171.yaml from the NIST OSCAL catalog.

Source: usnistgov/oscal-content, nist.gov/SP800-171/rev3/json/
        (vendored at data/vendor/sp800-171/NIST_SP800-171_rev3_catalog.json)

NIST publications are US Government works and not subject to copyright, so the
requirement titles are carried verbatim.

Two things this filters:

  * Withdrawn requirements. Rev 3 restructured heavily and OSCAL keeps the
    withdrawn items with a `status` property so the lineage stays traceable.
    They are not live requirements — dropping them takes 130 entries to 97.

  * Non-800-53 references. Each requirement links to back-matter resources, and
    those include NIST IRs and other documents alongside the 800-53 controls.
    Only things shaped like a control id become crosswalk edges.
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "data" / "vendor" / "sp800-171" / "NIST_SP800-171_rev3_catalog.json"
OUT = ROOT / "data" / "frameworks" / "sp800-171.yaml"
XW_OUT = ROOT / "data" / "mappings" / "sp800-171-crosswalk.yaml"
CONTROLS = ROOT / "data" / "controls.yaml"

PREFIX = "SP_800_171_"
# An 800-53 control id, optionally with an enhancement: AC-02, AC-02(03).
CTRL_RE = re.compile(r"^([A-Z]{2})-(\d+)(?:\((\d+)\))?$")


def esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def walk(node):
    """Yield every control, including nested ones."""
    for c in node.get("controls", []) or []:
        yield c
        yield from walk(c)


def is_withdrawn(control) -> bool:
    return any(
        p.get("name") == "status" and "ithdraw" in str(p.get("value", ""))
        for p in control.get("props", []) or []
    )


def normalise_control(title: str) -> str | None:
    """`AC-02(03)` -> `AC-2(3)`, matching our catalog. None if not a control id."""
    m = CTRL_RE.match(title.strip())
    if not m:
        return None
    fam, num, enh = m.group(1), int(m.group(2)), m.group(3)
    return f"{fam}-{num}" + (f"({int(enh)})" if enh else "")


def main() -> int:
    if not SRC.exists():
        print(f"missing source: {SRC}", file=sys.stderr)
        return 1

    cat = json.loads(SRC.read_text(encoding="utf8"))["catalog"]
    version = cat.get("metadata", {}).get("version", "")
    resources = {r["uuid"]: (r.get("title") or "") for r in cat.get("back-matter", {}).get("resources", [])}
    known = set(re.findall(r'code:\s*"([^"]+)"', CONTROLS.read_text(encoding="utf8")))

    families, requirements, mappings = [], [], []
    withdrawn = 0
    dropped_refs = 0

    for g in cat.get("groups", []):
        fam_code = g["id"].replace(PREFIX, "")
        families.append((fam_code, g.get("title", fam_code)))
        for c in walk(g):
            code = c["id"].replace(PREFIX, "")
            if is_withdrawn(c):
                withdrawn += 1
                continue
            requirements.append((code, c.get("title", ""), fam_code, g.get("title", fam_code)))
            seen = set()
            for link in c.get("links", []) or []:
                ref = resources.get(str(link.get("href", "")).lstrip("#"), "")
                ctrl = normalise_control(ref)
                if not ctrl:
                    continue  # an IR or other document, not an 800-53 control
                if ctrl in seen:
                    continue
                seen.add(ctrl)
                if ctrl not in known:
                    dropped_refs += 1
                    continue
                mappings.append((ctrl, code))

    requirements.sort()
    lines = [
        "# NIST SP 800-171 Rev 3 — Protecting Controlled Unclassified Information",
        "# ----------------------------------------------------------------------------",
        "# GENERATED by scripts/gen_sp800_171_catalog.py — do not edit by hand.",
        "#",
        "# Source: usnistgov/oscal-content, vendored at",
        "#   data/vendor/sp800-171/NIST_SP800-171_rev3_catalog.json",
        "#",
        "# NIST publications are US Government works and not subject to copyright, so",
        "# the requirement text is verbatim rather than paraphrased.",
        "#",
        f"# {len(families)} families, {len(requirements)} requirements.",
        f"# {withdrawn} withdrawn requirements dropped — Rev 3 restructured heavily and",
        "# OSCAL keeps the withdrawn entries so the lineage stays traceable.",
        "meta:",
        "  framework: NIST SP 800-171",
        '  version: "Rev 3"',
        "  # Off until an organisation adopts it; see frameworks.enabled.",
        "  enabled: false",
        "  licence: Public domain (US Government work, 17 USC 105)",
        "  source_url: https://csrc.nist.gov/pubs/sp/800/171/r3/final",
        "families:",
    ]
    for code, title in families:
        lines.append(f'  - {{ code: "{code}", title: "{esc(title)}" }}')
    lines.append("requirements:")
    for code, title, fam, fam_title in requirements:
        lines.append(
            f'  - {{ code: "{code}", family: "{fam}", family_title: "{esc(fam_title)}", title: "{esc(title)}" }}'
        )
    OUT.write_text("\n".join(lines) + "\n", encoding="utf8")
    print(
        f"wrote {OUT.relative_to(ROOT)}: {len(families)} families, "
        f"{len(requirements)} requirements ({withdrawn} withdrawn dropped)"
    )

    xw = [
        "# NIST 800-53 Rev 5 -> SP 800-171 Rev 3 crosswalk",
        "# ----------------------------------------------------------------------------",
        "# GENERATED by scripts/gen_sp800_171_catalog.py — do not edit by hand.",
        "#",
        "# 800-171 requirements are DERIVED from 800-53 controls and the OSCAL catalog",
        "# carries that lineage — a stronger relationship than CSF's informative",
        "# references, hence high confidence.",
        "#",
        "# But the link relation in the source is literally `reference`, not an",
        "# equivalence assertion, and many edges point at control ENHANCEMENTS that are",
        "# narrower than the requirement citing them. So these are `partial`, not",
        "# `equivalent`: the source says these are related by derivation, and upgrading",
        "# that to equivalence would inflate coverage on an assertion NIST did not make.",
        f"# {len(set(mappings))} edges; {dropped_refs} references dropped as controls absent from our CCF.",
        "sp800-171:",
    ]
    for ctrl, req in sorted(set(mappings)):
        xw.append(
            f'  - {{ control: "{ctrl}", requirement: "{req}", '
            f'relationship: "partial", confidence: "high", source: "oscal-derived" }}'
        )
    XW_OUT.write_text("\n".join(xw) + "\n", encoding="utf8")
    print(
        f"wrote {XW_OUT.relative_to(ROOT)}: {len(set(mappings))} edges "
        f"({dropped_refs} refs dropped — control not in our catalog)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
